= TODO

* [ ] Initialize state automatically on startup.
  ** [x] Secrets: JWK
  ** [x] SQLite Database
  ** [ ] Remove old `mensam-init`, which is redundant now.

* [ ] Run weeder as part of `nix flake check`.

* [ ] Email backend.
  ** [ ] Implement `EmailT` with an instance `MonadEmail`.
  ** [ ] Send a mail on registration.
    *** [ ] The registration mail may include a link to confirm the user's email.
      **** The registration should still be considered complete, even when the confirmation didn't happen yet. User's don't want to look into their mails before booking a desk.
      **** [ ] Database column in user table to track email confirmation.
      **** [ ] New backend route to handle this confirmation
      **** [ ] Frontend (URL, screen, API, ...) should be able to handle this confirmation link.

* [ ] `nixosConfigurations` can test the `nixosModule`.

* [ ] Add loading screen to HTML wrapper for frontend.

* [ ] Frontend: Add wrapper function that sets ALL font properties at once, so you cannot forget anything.

* [ ] Frontend: Add link to source code somewhere on the landing page. Maybe in a footer?
