= Server

The server executable is written in Haskell using wai and servant for the HTTP interface.
OpenAPI documentation is generated automatically.
This application uses mtl-style effects.
An SQLite database is used for persistent storage.

== Configuration

Environment variables and a configuration file change the runtime behaviour.

=== Environment

Environment variables are checked early during the initialization.
The options are set link:./source/library/Mensam/Server/Environment.hs[here].

=== Configuration file

The configuration file is written in JSON and is specified in link:./source/library/Mensam/Server/Configuration.hs[here].

== Database

The filepath for the SQLite database can be configured.
The database will be automatically initialized during the first startup.

=== Migrations

Currently there are no migrations yet.

[NOTE]
====
__The basic idea of a migration setup will be like this.__

Migrations will only be supported on major (?) version bumps.

During startup the server application checks the current version of the database.
If the database is outdated, then apply the migration and set the new version.

The database version can be tracked with a designated table in the database.

I don't know yet, whether it's a good idea to support version jumps (more than one major version).
====

== Development

[source,bash]
----
# Generate static files and configuration.
nix build ..#subflakes.final.packages.x86_64-linux.config

# Use cabal to develop the application.
MENSAM_CONFIG_FILE=result cabal run mensam-server -O0
----

=== Formatting

Use `fourmolu` to format Haskell.

[source,bash]
----
# Format Haskell.
fourmolu --mode inplace ./source
----

=== `weeder`

Running `weeder` should be a part of linting, but requires manual execution at the moment.

[source,bash]
----
# Prepare additional information for weeder.
cabal clean
cabal build all

# Run weeder.
weeder
----

=== `graphmod`

The module dependency graph can be visualised using `graphmod`.

[source,bash]
----
# Run graphmod.
nix build ..#subflakes.server.checks.x86_64-linux.graphmod

# View graph with xdot or your PDF viewer.
xdot result/graphmod.dot
zathura result/graphmod.pdf
----
