jobs:
  check-matrix:
    name: "Matrix to Check Flake"
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: "Set up GitHub Actions"
      uses: actions/checkout@v4.1.7
    - name: "Set up Nix"
      uses: cachix/install-nix-action@v27
    - name: "Set up Cachix"
      uses: cachix/cachix-action@v15
      with:
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        name: jumper149-mensam
    - id: set-matrix
      name: "Generate Nix Matrix"
      run: |
        set -Eeu
        matrix="$(nix eval --json '.#githubActions.matrix')"
        echo "matrix=$matrix" >> "$GITHUB_OUTPUT"
  check:
    name: "Check Flake"
    needs: check-matrix
    runs-on: ubuntu-latest
    steps:
    - name: "Set up GitHub Actions"
      uses: actions/checkout@v4.1.7
    - name: "Set up Nix"
      uses: cachix/install-nix-action@v27
      with:
        extra_nix_config: sandbox = relaxed
    - name: "Set up Cachix"
      uses: cachix/cachix-action@v15
      with:
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        name: jumper149-mensam
    - name: "Check"
      run: nix build ".#${{ matrix.attr }}" --print-build-logs
      if: ${{ matrix.sandbox }}
    - name: "Check (without sandbox)"
      run: nix build ".#${{ matrix.attr }}" --print-build-logs --option sandbox false
      if: ${{ ! matrix.sandbox }}
    strategy:
      fail-fast: false
      matrix: ${{fromJSON(needs.check-matrix.outputs.matrix)}}
name: "Default"
on:
  push:
