jobs:
  push-docker-image:
    name: "Build and push Docker Image to Docker Hub Registry"
    runs-on: ubuntu-latest
    steps:
    - name: "Set up GitHub Actions"
      uses: actions/checkout@v4.1.7
    - name: "Set up Nix"
      uses: cachix/install-nix-action@v27
    - name: "Set up Cachix"
      uses: cachix/cachix-action@v15
      with:
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        name: jumper149-mensam
    - name: "Log in to Docker Hub"
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: "Build Docker Image"
      run: nix build ".#dockerImages.default" --print-build-logs
    - name: "Load Docker Image"
      run: docker load --input result
    - name: "Set Docker Image Tag"
      run: docker tag mensam:${GITHUB_SHA} jumper149/mensam:${GITHUB_REF#refs/tags/}
    - name: "Push Docker Image to Docker Hub"
      run: docker push jumper149/mensam:${GITHUB_REF#refs/tags/}
name: "Release"
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+.[0-9]+'
